// Internal CWE id -> short human-readable name map. Covers the CWEs that Bandit
// (Python) and Semgrep (JavaScript) commonly emit, plus general OWASP ones.
// getCweName returns undefined for anything unknown so the UI can show nothing.
export const CWE_NAMES: Record<number, string> = {
  20: "Improper Input Validation",
  22: "Path Traversal",
  78: "OS Command Injection",
  79: "Cross-site Scripting (XSS)",
  88: "Argument Injection",
  89: "SQL Injection",
  90: "LDAP Injection",
  91: "XML Injection",
  93: "CRLF Injection",
  94: "Code Injection",
  95: "Eval Injection",
  113: "HTTP Response Splitting",
  116: "Improper Encoding or Escaping of Output",
  117: "Improper Output Neutralization for Logs",
  120: "Buffer Copy without Checking Size",
  190: "Integer Overflow or Wraparound",
  200: "Exposure of Sensitive Information",
  209: "Information Exposure Through an Error Message",
  215: "Sensitive Information in Debugging Code",
  250: "Execution with Unnecessary Privileges",
  259: "Use of Hard-coded Password",
  269: "Improper Privilege Management",
  276: "Incorrect Default Permissions",
  285: "Improper Authorization",
  295: "Improper Certificate Validation",
  297: "Certificate Validation with Host Mismatch",
  300: "Channel Accessible by Non-Endpoint",
  310: "Cryptographic Issues",
  311: "Missing Encryption of Sensitive Data",
  312: "Cleartext Storage of Sensitive Information",
  319: "Cleartext Transmission of Sensitive Information",
  321: "Use of Hard-coded Cryptographic Key",
  326: "Inadequate Encryption Strength",
  327: "Broken or Risky Cryptographic Algorithm",
  328: "Use of Weak Hash",
  329: "Not Using a Random IV with CBC Mode",
  330: "Use of Insufficiently Random Values",
  331: "Insufficient Entropy",
  338: "Cryptographically Weak PRNG",
  345: "Insufficient Verification of Data Authenticity",
  347: "Improper Verification of Cryptographic Signature",
  352: "Cross-Site Request Forgery (CSRF)",
  362: "Race Condition",
  367: "Time-of-check Time-of-use (TOCTOU) Race Condition",
  377: "Insecure Temporary File",
  379: "Temp File in Directory with Incorrect Permissions",
  400: "Uncontrolled Resource Consumption",
  415: "Double Free",
  416: "Use After Free",
  425: "Direct Request (Forced Browsing)",
  434: "Unrestricted Upload of Dangerous File Type",
  476: "NULL Pointer Dereference",
  477: "Use of Obsolete Function",
  489: "Active Debug Code",
  494: "Download of Code Without Integrity Check",
  501: "Trust Boundary Violation",
  502: "Deserialization of Untrusted Data",
  521: "Weak Password Requirements",
  522: "Insufficiently Protected Credentials",
  532: "Sensitive Information in Log File",
  601: "Open Redirect",
  605: "Multiple Binds to the Same Port",
  611: "XML External Entity (XXE)",
  613: "Insufficient Session Expiration",
  614: "Sensitive Cookie Without 'Secure' Attribute",
  640: "Weak Password Recovery Mechanism",
  643: "XPath Injection",
  703: "Improper Handling of Exceptional Conditions",
  730: "Denial of Service",
  732: "Incorrect Permission Assignment for Critical Resource",
  759: "One-Way Hash without a Salt",
  760: "One-Way Hash with a Predictable Salt",
  776: "XML Entity Expansion (Billion Laughs)",
  787: "Out-of-bounds Write",
  798: "Use of Hard-coded Credentials",
  835: "Loop with Unreachable Exit Condition (Infinite Loop)",
  838: "Inappropriate Encoding for Output Context",
  862: "Missing Authorization",
  863: "Incorrect Authorization",
  915: "Mass Assignment",
  918: "Server-Side Request Forgery (SSRF)",
  943: "Improper Neutralization in Data Query Logic",
  1004: "Sensitive Cookie Without 'HttpOnly' Flag",
  1236: "CSV Formula Injection",
  1333: "Inefficient Regular Expression Complexity (ReDoS)",
};

/** Returns the CWE short name, or undefined when the id is unknown/missing. */
export function getCweName(id?: number | string | null): string | undefined {
  if (id === undefined || id === null) return undefined;
  const n = typeof id === "string" ? parseInt(id, 10) : id;
  if (!Number.isFinite(n) || n <= 0) return undefined;
  return CWE_NAMES[n];
}
