const crypto = require('crypto');

/**
 * Generates a cryptographically secure random token.
 * * Security Features:
 * - Uses CSPRNG (crypto.randomBytes)
 * - 256 bits of entropy (32 bytes)
 * - Base64url encoded for URL/Header safety
 * * @returns {string} The raw token to be returned to the client.
 */
function generateSecureToken() {
  // 1. Generate 32 bytes of high-entropy randomness
  const buffer = crypto.randomBytes(32);

  // 2. Encode to base64url (replaces +, /, and = for safe transmission)
  const rawToken = buffer
    .toString('base64')
    .replace(/\+/g, '-')
    .replace(/\//g, '_')
    .replace(/=/g, '');

  // 3. Return only the raw token to the immediate caller
  return rawToken;
}

/**
 * Prepares the token for database storage.
 * * @param {string} token - The raw token generated by generateSecureToken
 * @returns {string} The SHA-256 hash to be stored in the DB
 */
function hashTokenForStorage(token) {
  return crypto
    .createHash('sha256')
    .update(token)
    .digest('hex');
}

// --- Usage Example ---
const token = generateSecureToken();

// DO: Send this to the user via Secure/HttpOnly cookie or JSON response
console.log(`Token generated: [REDACTED]`); 

// DO: Store this in your database
const hashedToken = hashTokenForStorage(token);

// NEVER: log the 'token' variable directly in production logs